title = "TeleportQueue"
gitRepoUrl = "https://github.com/mvyasu/TeleportQueue"

gitSourceBranch = "main"
changelog = true
classOrder = []

[docusaurus]
favicon = "/favicon.ico"
onBrokenLinks = "warn"
onBrokenMarkdownLinks = "warn"

organizationName = "mvyasu"
projectName = "TeleportQueue"
tagline = "A module that allows developers to quickly setup a teleport queue in Roblox."