title = "TeleportQueue"
gitRepoUrl = "https://github.com/mvyasu/TeleportQueue"

gitSourceBranch = "main"
changelog = true
classOrder = ["TeleportQueue"]

[docusaurus]
onBrokenLinks = "warn"
onBrokenMarkdownLinks = "warn"

organizationName = "mvyasu"
projectName = "TeleportQueue"
url = "https://mvyasu.github.io"
baseUrl = "/TeleportQueue"
tagline = "A module that allows developers to quickly setup a teleport queue in Roblox"